Repository commercialhaskell/stack, pull requests merged in 2018-06, with the labels that each got.

#4053 4051 - Add stack maintainer team process documentation
  doc/maintainers/releases.md
  doc/maintainers/team_process.md
  etc/scripts/README.md
  mkdocs.yml
Labels: component: documentation, type: discuss

#4103 4039 namespaced templates
  ChangeLog.md
  doc/GUIDE.md
  src/Stack/New.hs
  src/Stack/Options/NewParser.hs
  src/Stack/Types/TemplateName.hs
Labels: needs changes

#4106 Re #4091: Pre-Windows 10, default --color=never
  ChangeLog.md
  package.yaml
  src/Stack/Options/Completion.hs
  src/Stack/Options/GlobalParser.hs
  src/main/Main.hs
  src/unix/Stack/DefaultColorWhen.hs
  src/windows/Stack/DefaultColorWhen.hs
  stack.yaml
Labels: awaiting review, component: windows

#4074 get-stack: check deps before sudo
  etc/scripts/get-stack.sh
Labels: awaiting review, awaiting-response
