Repository commercialhaskell/stack, pull requests merged in 2018-11, with the labels that each got.

#4381 Allow variables in filenames in templates
  ChangeLog.md
  src/Stack/New.hs
  test/integration/lib/StackTest.hs
  test/integration/tests/variables-in-template-file-names/Main.hs
  test/integration/tests/variables-in-template-file-names/files/.gitignore
  test/integration/tests/variables-in-template-file-names/files/template.hsfiles
Labels: ready-to-merge, type: enhancement

#4339 Add option to print dependencies as tree
  ChangeLog.md
  src/Stack/Dot.hs
  src/Stack/Options/DotParser.hs
  test/integration/tests/4101-dependency-tree/Main.hs
  test/integration/tests/4101-dependency-tree/files/files.cabal
  test/integration/tests/4101-dependency-tree/files/src/Main.hs
  test/integration/tests/4101-dependency-tree/files/stack.yaml
Labels: need test

#4268 To prevent download ghc when using `stack clean`.
  ChangeLog.md
  src/Stack/Config.hs
  src/Stack/Runners.hs
  src/Stack/Setup.hs
  src/Stack/Types/Config.hs
  src/main/Main.hs
  test/integration/tests/4181-clean-wo-dl-ghc/Main.hs
  test/integration/tests/4181-clean-wo-dl-ghc/files/foo.cabal
  test/integration/tests/4181-clean-wo-dl-ghc/files/stack.yaml
Labels: awaiting review, needs changes, work-in-progress
