Repository commercialhaskell/stack, pull requests merged in 2018-07, with the labels that each got.

#4108 Fix issues with stderr being inherited by child processes
  src/Stack/Coverage.hs
  src/Stack/Hoogle.hs
  src/Stack/Setup.hs
  src/Stack/Setup/Installed.hs
  src/Stack/Solver.hs
Labels: awaiting-response

#4127 Point to user's config.yaml when advising 'allow-newer: true'
  ChangeLog.md
  src/Stack/Build/ConstructPlan.hs
  test/integration/tests/3685-config-yaml-for-allow-newer/Main.hs
  test/integration/tests/3685-config-yaml-for-allow-newer/files/files.cabal
  test/integration/tests/3685-config-yaml-for-allow-newer/files/src/Src.hs
Labels: awaiting review, awaiting-response, in progress, work-in-progress

#4132 Use a hard-coded tool dependency map (fixes #4125)
  ChangeLog.md
  src/Stack/Build/ConstructPlan.hs
  src/Stack/Build/Source.hs
  src/Stack/BuildPlan.hs
  src/Stack/Package.hs
  src/Stack/Snapshot.hs
  src/Stack/Types/BuildPlan.hs
  src/Stack/Types/Package.hs
Labels: awaiting-response

#4167 Fix behavior of --no-signature to turn signing off
  ChangeLog.md
  doc/yaml_configuration.md
  src/Stack/Config.hs
  src/Stack/Options/SDistParser.hs
  src/Stack/Types/Config.hs
  src/Stack/Upload.hs
  src/main/Main.hs
  test/integration/tests/upload/Main.hs
  test/integration/tests/upload/files/FakeHackage.hs
  test/integration/tests/upload/files/FakeHackageStart.hs
  test/integration/tests/upload/files/Foo.hs
  test/integration/tests/upload/files/gpg-disabled/gpg
  test/integration/tests/upload/files/gpg-disabled/gpg2
  test/integration/tests/upload/files/stack.yaml
  test/integration/tests/upload/files/uploadtest.cabal
Labels: awaiting review

#4168 Issue #4039 - Spec for template name parsing in `stack new`
  src/test/Stack/Types/TemplateNameSpec.hs
Labels: awaiting review

#4173 Use cached template if template download fails
  ChangeLog.md
  src/Network/HTTP/Download.hs
  src/Stack/New.hs
  test/integration/tests/3850-cached-templates-network-errors/Main.hs
Labels: awaiting-response, in progress
